### ISSUE TITLE
Do you have a plan to support HBase2?

### ISSUE THREAD

**Issue by mwkang** [kakao/hbase-packet-inspector#3]
안녕하세요.

좋은 오픈소스 프로젝트를 만들어주셔서 감사합니다.
혹시 HBase 2.X 버전을 지원할 계획이 있는지 궁금합니다.

감사합니다.

----

Hello

Thank you for creating a good open source project.
I wonder if you have any plans to support HBase 2.X version.

Thanks.

**Comment by junegunn** [comment]
Hi, thanks for your interest in the project.

Yes, we will definitely support HBase 2, but we don't have a specific ETA at the moment. We will let you know of any updates.

**Comment by mwkang** [comment]
Thanks you for kindly response.
